services:
  my-notebook:
    image: slowpokeislife/my-datascience-notebook:1.0
    ports:
      - "8889:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''

  pyspark:
    image: quay.io/jupyter/pyspark-notebook
    ports:
      - "8890:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''

